kind: pipeline
name: default

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: build
    image: cimg/go:1.22.6

    volumes:
    - name: dockersock
      path: /var/run/docker.sock

    environment:
      GITEA_TOKEN:
        from_secret: gitea_token

    commands:
      - sudo chmod 666 /var/run/docker.sock
      - sudo chown -R circleci:circleci .
      - curl -sfL https://goreleaser.com/static/run | bash -s -- check

trigger:
  event:
    - tag

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
