version: 2

before:
  hooks:
    - sudo apt update
    - sudo apt install rpm
    - go mod tidy
    - go mod download
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
      - windows
    goarch:
      - amd64

archives:
  - format: zip

nfpms:
  -
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    # Default is empty.
    vendor: Kazuhiro MUSASHI

    # Your app's homepage.
    # Default is empty.
    homepage: https://blog.kazu634.com/

    # Your app's maintainer (probably you).
    # Default is empty.
    maintainer: Kazuhiro Musashi <simoom634@yahoo.co.jp>

    # Formats to be generated:
    formats:
      - deb
      - rpm

release:
  gitea:
    owner: kazu634
    name: moneyforward

  disable: false
  mode: append

gitea_urls:
  api: https://gitea.kazu634.com/api/v1/
  download: https://gitea.kazu634.com

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  use: gitea

dockers:
  -
    image_templates:
      - reg.kazu634.com/kazu634/{{ .ProjectName }}:{{ .Tag }}
      - reg.kazu634.com/kazu634/{{ .ProjectName }}:latest

    goos: linux
    goarch: amd64

    dockerfile: Dockerfile

    skip_push: false
    skip_build: false

    push_flags:
      - --tls-verify=false
